Fix Go import path (#132)
https://github.com/pulumi/pulumi-std/actions/runs/21693671622/job/62559821737
```
Run git push origin "sdk/v2.3.0-alpha.1770250848+6906400"
To https://github.com/pulumi/pulumi-std
 * [new tag]         sdk/v2.3.0-alpha.1770250848+6906400 -> sdk/v2.3.0-alpha.1770250848+6906400
Run mkdir pulumi-publish-go-sdk-action-fetch
go: creating new go.mod: module github.com/pulumi/publish-go-sdk-action/fetch
go: github.com/pulumi/pulumi-std/sdk/v2@v2.3.0-alpha.1770250848+6906400: github.com/pulumi/pulumi-std/sdk@v2.3.0-alpha.1770250848.0.20260205003121-69617b70f8b8: invalid version: module contains a go.mod file, so module path must match major version ("github.com/pulumi/pulumi-std/sdk/v2")
Error: Process completed with exit code 1.
```

Go SDK publishing was failing due to the missing v2 suffix on the
module.

This fixes the module's path and also adopts the `respectSchemaVersion`
pattern we use for other providers.